name: Playwright tests

on: workflow_dispatch
  
  #schedule: # Schedule the job to run at 12am every day
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # - name: Install Playwright
      #   run: npx playwright install --with-deps chromium
      - name: Download latest tests results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: artifact_id=$(gh api -X GET '/repos/tempest-tech-ltd/autoconsent/actions/artifacts' -F per_page=1 -F name="playwright-report" -q ".artifacts[0].id")
      - name: Display latest artifact ID
        run: echo "Artifact ID:"
        run: echo $artifact_id
      - name: Create a fake File
        run: echo "Hello world" > file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: file.txt

      # - name: Run Playwright tests
      #   run: npx playwright test --project chrome --reporter=html
      # # Upload the test result artifacts
      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30