name: Playwright tests

on: workflow_dispatch
  
  #schedule: # Schedule the job to run at 12am every day
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        #run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json playwright test --project chrome --reporter=json
        run: playwright test --project chrome --reporter=html
      # Upload the test result artifacts
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30